version: '3.8'

services:

  web:
    build:
        context: app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/TP_DB.sql:/docker-entrypoint-initdb.d/TP_DB.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/certs:/certs
    ports:
      - "80:80"
      - "443:443"
   
